### ISSUE TITLE
Server configuration not documented?

### ISSUE THREAD

**Issue by rbtcollins** [networknt/microservices-framework-benchmark#37]
I can't see where the server configuration is documented. Is it single threaded servers or multithreaded? Does the test machine have enough cores to let the servers run uncontended with the test workload?

**Comment by stevehu** [comment]
@rbtcollins There are multiple frameworks in this repository and every framework will have its configuration built-in so that we can just start the server with a command line without worrying too much about the server config. Some of the frameworks will have parameters to pass in and it is documented clearly in the README.md

The test machine has 4 cores and the client is running on the same machine in order to eliminate the network fluctuations. It is just a way to test the throughput for each framework under the cpu constraint. I am planning to rerun all the test again on my server with contains 20 cores with 192GB memory. Just need to find time to do that :)
